# Generated by Django 5.2.6 on 2025-10-15 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria_Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_insumo_nombre', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Categoría de Insumo',
                'verbose_name_plural': 'Categorías de Insumos',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_nombre', models.CharField(max_length=200)),
                ('producto_descripcion', models.CharField(max_length=200)),
                ('producto_precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto_disponible', models.BooleanField(default=True)),
                ('producto_fecha_hora_creacion', models.DateTimeField(auto_now_add=True)),
                ('producto_imagen', models.ImageField(blank=True, null=True, upload_to='inventario/images')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Tipo_Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_producto_nombre', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Tipo de Producto',
                'verbose_name_plural': 'Tipos de Productos',
            },
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insumo_nombre', models.CharField(max_length=200)),
                ('insumo_unidad', models.CharField(max_length=50)),
                ('insumo_stock', models.DecimalField(decimal_places=2, max_digits=10)),
                ('insumo_stock_minimo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('insumo_precio_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoria_insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.categoria_insumo')),
            ],
            options={
                'verbose_name': 'Insumo',
                'verbose_name_plural': 'Insumos',
            },
        ),
        migrations.CreateModel(
            name='Producto_X_Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_insumo_cantidad', models.DecimalField(decimal_places=3, max_digits=10)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.insumo')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
            ],
            options={
                'verbose_name': 'Producto por Insumo',
                'verbose_name_plural': 'Productos por Insumos',
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.tipo_producto'),
        ),
    ]
