# Generated by Django 5.2.6 on 2025-10-17 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='producto_imagen_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='producto_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
