# Generated by Django 5.2.6 on 2025-10-17 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_producto_producto_imagen_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='tipo_producto',
            field=models.ForeignKey(default='Sin Especificar', on_delete=django.db.models.deletion.PROTECT, to='inventario.tipo_producto'),
        ),
    ]
