# Generated by Django 5.2.6 on 2025-10-20 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_alter_producto_tipo_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='producto_imagen_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
