# Generated by Django 5.2.6 on 2025-10-20 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_alter_producto_producto_imagen_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='producto_imagen_url',
            field=models.URLField(blank=True, max_length=5000, null=True),
        ),
    ]
