# Generated by Django 5.2.6 on 2025-10-21 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_alter_producto_producto_imagen_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='insumo_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='insumos/'),
        ),
        migrations.AddField(
            model_name='insumo',
            name='insumo_imagen_url',
            field=models.URLField(blank=True, max_length=5000, null=True),
        ),
    ]
