# Generated by Django 5.2.6 on 2025-10-23 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_insumo_insumo_imagen_insumo_insumo_imagen_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='insumo_imagen_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='producto_imagen_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
