# Generated by Django 5.2.6 on 2025-10-23 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_alter_insumo_insumo_imagen_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insumo',
            name='insumo_precio_compra',
        ),
    ]
