# Generated by Django 5.2.6 on 2025-09-10 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combo_nombre', models.CharField(max_length=200)),
                ('combo_precio', models.FloatField()),
            ],
            options={
                'verbose_name': 'Combo',
                'verbose_name_plural': 'Combos',
            },
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promocion_nombre', models.CharField(max_length=100)),
                ('promocion_precio', models.FloatField()),
                ('promocion_fecha_hora_inicio', models.DateTimeField()),
                ('promocion_fecha_hora_fin', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Promocion',
                'verbose_name_plural': 'Promociones',
            },
        ),
        migrations.CreateModel(
            name='Producto_Combo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_combo_cantidad', models.IntegerField()),
                ('producto_combo_precio', models.FloatField()),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prom_comb.combo')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
            ],
            options={
                'verbose_name': 'Producto Combo',
                'verbose_name_plural': 'Productos Combos',
            },
        ),
        migrations.CreateModel(
            name='Producto_Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_promocion_cantidad', models.IntegerField()),
                ('producto_promocion_precio', models.FloatField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
                ('promocion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prom_comb.promocion')),
            ],
            options={
                'verbose_name': 'Producto Promocion',
                'verbose_name_plural': 'Productos Promociones',
            },
        ),
    ]
