# Generated by Django 5.2.6 on 2025-09-05 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor_dni', models.CharField(max_length=100, unique=True)),
                ('proveedor_nombre', models.CharField(max_length=100)),
                ('proveedor_direccion', models.CharField(max_length=200)),
                ('proveedor_telefono', models.CharField(max_length=20)),
                ('proveedor_email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
    ]
