# Generated by Django 5.2.6 on 2025-10-15 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('caja', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Egreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('egreso_descripcion', models.CharField(max_length=200)),
                ('egreso_monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('egreso_fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caja.caja')),
            ],
            options={
                'verbose_name': 'Egreso',
                'verbose_name_plural': 'Egresos',
            },
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingreso_descripcion', models.CharField(max_length=200)),
                ('ingreso_monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ingreso_fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caja.caja')),
            ],
            options={
                'verbose_name': 'ingreso',
                'verbose_name_plural': 'ingresos',
            },
        ),
    ]
