# Generated by Django 5.2.6 on 2025-09-10 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_dni', models.CharField(max_length=200, unique=True)),
                ('cliente_nombre', models.CharField(max_length=200)),
                ('cliente_apellido', models.CharField(max_length=200)),
                ('cliente_telefono', models.CharField(max_length=200)),
                ('cliente_direccion', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
