# Generated by Django 5.2.6 on 2025-10-28 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cliente_apellido',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cliente_dni',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cliente_email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
    ]
