# Generated by Django 5.2.6 on 2025-11-02 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compra", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proveedor",
            name="proveedor_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="proveedor",
            name="proveedor_telefono",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
