# Generated by Django 5.2.6 on 2025-11-07 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compra", "0003_alter_proveedor_proveedor_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proveedor",
            name="proveedor_direccion",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="proveedor",
            name="proveedor_dni",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
