# Generated by Django 5.2.6 on 2025-10-15 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promocion_nombre', models.CharField(max_length=100)),
                ('promocion_precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('promocion_fecha_hora_inicio', models.DateTimeField(blank=True, null=True)),
                ('promocion_fecha_hora_fin', models.DateTimeField(blank=True, null=True)),
                ('promocion_stock', models.IntegerField()),
                ('promocion_descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Promocion',
                'verbose_name_plural': 'Promociones',
            },
        ),
        migrations.CreateModel(
            name='Producto_Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
                ('promocion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_promocion', to='promocion.promocion')),
            ],
            options={
                'verbose_name': 'Producto Promocion',
                'verbose_name_plural': 'Productos Promociones',
            },
        ),
    ]
