# Generated by Django 5.2.6 on 2025-10-20 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promocion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto_promocion',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
