# Generated by Django 5.2.6 on 2025-10-25 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promocion', '0002_producto_promocion_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocion',
            name='promocion_estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='promocion',
            name='promocion_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='promociones/'),
        ),
        migrations.AddField(
            model_name='promocion',
            name='promocion_imagen_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
