# Generated by Django 5.2.6 on 2025-10-25 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promocion', '0003_promocion_promocion_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocion',
            name='promocion_imagen',
        ),
    ]
