# Generated by Django 5.2.6 on 2025-10-30 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("venta", "0002_alter_venta_caja_alter_venta_cliente"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venta",
            name="venta_medio_pago",
            field=models.CharField(
                choices=[("efectivo", "Efectivo"), ("transferencia", "Transferencia")],
                default="efectivo",
                max_length=20,
            ),
        ),
    ]
