# Generated by Django 5.2.6 on 2025-10-15 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caja_estado', models.BooleanField(default=True)),
                ('caja_monto_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('caja_saldo_final', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('caja_fecha_hora_apertura', models.DateTimeField(auto_now_add=True)),
                ('caja_fecha_hora_cierre', models.DateTimeField(blank=True, null=True)),
                ('caja_observacion', models.CharField(blank=True, max_length=400, null=True)),
            ],
            options={
                'verbose_name': 'Caja',
                'verbose_name_plural': 'Cajas',
            },
        ),
    ]
