# Generated by Django 5.2.6 on 2025-09-05 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caja_estado', models.BooleanField(default=True)),
                ('caja_monto_inicial', models.FloatField(default=0)),
                ('caja_saldo_final', models.FloatField(blank=True, default=0, null=True)),
                ('caja_fecha_hora_apertura', models.DateTimeField(auto_now=True)),
                ('caja_fecha_hora_cierre', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Caja',
                'verbose_name_plural': 'Cajas',
            },
        ),
    ]
