# Generated by Django 5.2.6 on 2025-10-15 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('caja', '0001_initial'),
        ('empleado', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleado.empleado'),
        ),
    ]
