# Generated by Django 5.2.6 on 2025-09-29 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol_nombre', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empleado_dni', models.CharField(max_length=100, unique=True)),
                ('empleado_nombre', models.CharField(max_length=30)),
                ('empleado_apellido', models.CharField(max_length=30)),
                ('empleado_telefono', models.CharField(max_length=100)),
                ('empleado_email', models.EmailField(max_length=254)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empleado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
            },
        ),
        migrations.CreateModel(
            name='Empleado_x_rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleado.empleado')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleado.rol')),
            ],
            options={
                'verbose_name': 'Empleado por Rol',
                'verbose_name_plural': 'Empleados por Roles',
            },
        ),
    ]
