# Generated by Django 5.2.6 on 2025-09-10 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rol_Empleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol_nombre', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Rol de empleado',
                'verbose_name_plural': 'Roles de empleados',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empleado_dni', models.CharField(max_length=100, unique=True)),
                ('empleado_nombre', models.CharField(max_length=30)),
                ('empleado_apellido', models.CharField(max_length=30)),
                ('empleado_telefono', models.CharField(max_length=100)),
                ('rol_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleado.rol_empleados')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
            },
        ),
    ]
