# Generated by Django 5.2.6 on 2025-10-18 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='failed_login_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='empleado',
            name='lockout_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
