# Generated by Django 5.2.6 on 2025-09-10 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rol_Empleados',
            new_name='Rol_Empleado',
        ),
    ]
