# Generated by Django 5.2.6 on 2025-10-24 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_detalle_pedido_cantidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_pedido',
            name='notas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detalle_pedido',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='detalle_pedido',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
