# Generated by Django 5.2.6 on 2025-10-25 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_remove_insumo_insumo_precio_compra'),
        ('pedido', '0003_detalle_pedido_notas_alter_detalle_pedido_cantidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_pedido',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.producto'),
        ),
    ]
