# Generated by Django 5.2.6 on 2025-10-28 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_alter_cliente_cliente_apellido_and_more'),
        ('pedido', '0004_alter_detalle_pedido_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='cliente.cliente'),
        ),
    ]
